### ISSUE TITLE
Scaling on Android mobile devices

### ISSUE THREAD

**Issue by kaffeetrinken** [ronoc/forwind.net#53]
Scaling on Android mobile devices need improvements (see screenshots attached)
Layout doesn't jump to on column design, menu is too small.

on small breakpoint, images keep a max-width. is it possible to scale them 100% width? (last image)

![screenshot_20180305-200711](https://user-images.githubusercontent.com/16975700/37571806-e7d09ca8-2b01-11e8-8d84-811242f9608b.png)
![screenshot_20180305-200640](https://user-images.githubusercontent.com/16975700/37571807-edc6cf60-2b01-11e8-9172-b1e0bbb2a79d.png)
![screenshot_20180305-200654](https://user-images.githubusercontent.com/16975700/37571808-f66b489e-2b01-11e8-90d8-90d427912716.png)

====================================

![screen shot 2018-03-18 at 23 06 27](https://user-images.githubusercontent.com/16975700/37571812-00b632b4-2b02-11e8-829d-6bbbc842ed93.png)

**Comment by ramonjd** [comment]
Think I fixed most of these, assuming correct interpretation of issue notes:

> is it possible to scale them 100% width? (last image)

As per the last image? 👍 

> Layout doesn't jump to on column design

Not sure what this means, but I think most of the issues are fixed in relation to layout

> menu is too small.

Most of the font and size issues were due to the fact that I forgot to set the viewport scale in the meta

https://github.com/ronoc/forwind.net/commit/d1259d135f92eb9096028491c90ffc9dda4efdf4
